repos:
- repo: ssh://git@stash.cudaops.com:7999/bncoi/pre-commit-terraform.git
  rev: v1.50.0
  hooks:
    - id: terraform_fmt
      #- id: terraform_validate
    - id: terraform_tflint
      args:
          - '--args=--disable-rule=terraform_module_pinned_source'
    - id: terraform_docs_without_aggregate_type_defaults
